routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// 
use App\Http\Controllers\MovieController;
use App\Http\Controllers\GenreController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::resource('movies', MovieController::class);

Route::get('/',[MovieController::class, 'indexMovie'])->name('indexMovie');
Route::get('/create',[MovieController::class, 'createMovie'])->name('createMovie');
Route::post('store/',[MovieController::class, 'storeMovie'])->name('storeMovie');
Route::get('showMovie/{movie}',[MovieController::class, 'showMovie'])->name('showMovie');
Route::get('edit/{movie}',[MovieController::class, 'editMovie'])->name('editMovie');
Route::put('edit/{movie}',[MovieController::class, 'updateMovie'])->name('updateMovie');
Route::delete('/{movie}',[MovieController::class, 'destroyMovie'])->name('destroyMovie');


Route::resource('genres', GenreController::class);
Route::get('/',[GenreController::class, 'index'])->name('index');
Route::get('/create',[GenreController::class, 'create'])->name('create');
Route::post('store/',[GenreController::class, 'store'])->name('store');
Route::get('showGenre/{genre}',[GenreController::class, 'show'])->name('show');
Route::get('editGenre/{genre}',[GenreController::class, 'edit'])->name('edit');
Route::put('editGenre/{genre}',[GenreController::class, 'update'])->name('update');
Route::delete('/{genre}',[GenreController::class, 'destroyGenre'])->name('destroyGenre');

resources/views/crudMovie/createMovie.blade.php
@extends('layoutMovie')
    
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Movie</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ url('/') }}"> Back</a>
        </div>
    </div>
</div>
      
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{ route('storeMovie') }}" method="POST" enctype="multipart/form-data">
    @csrf
     <div class="row">
        
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                <input type="text" name="title" class="form-control" placeholder="Title">
            </div>
        </div> 

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Movie Url:</strong>
                <input type="text" name="movie_url" class="form-control" placeholder="Movie Url">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Thumbnail:</strong>
                <input type="file" name="thumbnail" class="form-control" placeholder="Thumbnail">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="Description"></textarea>
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Language:</strong>
                <input type="text" name="language" class="form-control" placeholder="Language">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Year:</strong>
                <input type="text" name="year" class="form-control" placeholder="Year">
            </div>
        </div>
    
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
      
</form>
@endsection

resources/views/crudMovie/editMovie.blade.php
@extends('layoutMovie')
  
@section('content')

<!-- Date Picker Link -->
<link href="https://netdna.bootstrapcdn.com/bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/css/datepicker.min.css" rel="stylesheet">
<!-- Date Picker script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://netdna.bootstrapcdn.com/bootstrap/2.3.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/js/bootstrap-datepicker.min.js"></script>
<div class="bg-light m-4 p-4 rounded">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Movie</h2>
            </div>
           
        </div>
    </div>
      
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
     
    <form action="{{ route('updateMovie',$movie->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Title:</strong>
            <input type="text" name="title" value="{{ $movie->title }}" class="form-control" placeholder="Title">
        </div>
    </div> 
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Movie Url:</strong>
            <input type="text" name="movie_url" value="{{ $movie->movie_url }}" class="form-control" placeholder="Movie Url">
        </div>
    </div>

    <!-- Image -->
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Thumbnail:</strong>
            <input type="file" name="thumbnail" value="/images/thumbnails/{{ $movie->thumbnail }}" class="form-control" placeholder="Thumbnail">
            <br>
            <img src="/images/thumbnails/{{ $movie->thumbnail }}" width="500px">

        </div>
    </div>
    <br>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Description:</strong>
            <textarea class="form-control" style="height:150px" name="description" placeholder="Description">{{ $movie->description }}</textarea>
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Year:</strong>
                <input type="text" name="year" value="{{ $movie->year }}" class="form-control" placeholder="Year">
            </div>
        </div>
        <!-- Dates -->
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Created At:</strong>
                {{ $movie->created_at->format('m/d/Y H:i') }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Updated At:</strong>
                {{ $movie->updated_at->format('m/d/Y H:i') }}
            </div>
        </div>
        <!-- Buttons -->
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button> 
            <a class="btn btn-secondary" href="{{ route('indexMovie') }}"> Back</a>
        </div>
    </form>
</div>  

@endsection

resources/views/crudMovie/indexMovie.blade.php
@extends('layoutMovie')

@section('content')
    <div class="col-lg-12">
        <div class="pull-left">
            <h2>Hanflix | Watch Movie for free | Livestream</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('movies.create') }}"> Create New Movie</a>
        </div>
    </div>


@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif

<table class="table table-bordered">
    <tr>
        <th>Thumbnail</th>
        <th>Title</th>
        <th>Movie Url</th>
        <th>Description</th>
        <th>Language</th>
        <th>Year</th>
        <th>Created at</th>
        <th>Updated at</th>
        <th width="280px">Action</th>
    </tr>

    @foreach ($movies as $movie)
    <tr>

        <!-- <td>{{ ++$i }}</td> -->
        <td><img src="/images/thumbnails/{{ $movie->thumbnail }}" width="100px"></td>
        <td>{{ $movie->title }}</td>
        <td>{{ $movie->movie_url }}</td>
        <td>{{ $movie->description }}</td>
        <td>{{ $movie->language }}</td>
        <td>{{ $movie->year }}</td>
        <td>{{ $movie->created_at->format('m/d/Y H:i') }}</td>
        <td>{{ $movie->updated_at->format('m/d/Y H:i') }}</td>
        <td>
            <form action="{{ route('destroyMovie',$movie->id) }}" method="POST">
                <a class="btn btn-warning" href="{{ route('showMovie',$movie->id) }}">Show</a>
                <a class="btn btn-info" href="{{ route('editMovie',$movie->id) }}">Edit</a>
                @csrf

                @method('DELETE')
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </td>
    </tr>
    @endforeach

</table>
{!! $movies->links() !!}
@endsection

resources/views/crudMovie/layoutMovie.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap Link -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

  <title>Hanflix | Watch Movie for free | Livestream</title>
</head>
<body>
  <div class="container">
    @yield('content')
  </div>
</body>
</html>

resources/views/crudMovie/showMovie.blade.php
@extends('layoutMovie')
  
@section('content')
<div class="bg-light m-4 p-4 rounded">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Movie</h2>
            </div>
        </div>
    </div>
          
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Title:</strong>
                  {{ $movie->title }}
              </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Movie Url:</strong>
                  {{ $movie->movie_url }}
              </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Thumbnail:</strong><br>
                  <img src="/images/thumbnails/{{ $movie->thumbnail }}" width="500px">
              </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Description:</strong>
                  {{ $movie->description }}
              </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Year:</strong>
                  {{ $movie->year }}
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Date Created:</strong>
                  {{ $movie->created_at->format('m/d/Y H:i') }}
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Date Updated:</strong>
                  {{ $movie->updated_at->format('m/d/Y H:i') }}
              </div>
          </div>
    </div>
    <div class="mt-4">
        <a class="btn btn-primary" href="{{ route('editMovie',$movie->id) }}">Edit</a>
        <a class="btn btn-secondary" href="{{ route('indexMovie') }}"> Back</a>
    </div> 
</div>
@endsection