routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// 
use App\Http\Controllers\MovieController;
use App\Http\Controllers\GenreController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::resource('movies', MovieController::class);

Route::get('/',[MovieController::class, 'indexMovie'])->name('indexMovie');
Route::get('/create',[MovieController::class, 'createMovie'])->name('createMovie');
Route::post('store/',[MovieController::class, 'storeMovie'])->name('storeMovie');
Route::get('showMovie/{movie}',[MovieController::class, 'showMovie'])->name('showMovie');
Route::get('edit/{movie}',[MovieController::class, 'editMovie'])->name('editMovie');
Route::put('edit/{movie}',[MovieController::class, 'updateMovie'])->name('updateMovie');
Route::delete('/{movie}',[MovieController::class, 'destroyMovie'])->name('destroyMovie');


Route::resource('genres', GenreController::class);
Route::get('/',[GenreController::class, 'index'])->name('index');
Route::get('/create',[GenreController::class, 'create'])->name('create');
Route::post('store/',[GenreController::class, 'store'])->name('store');
Route::get('showGenre/{genre}',[GenreController::class, 'show'])->name('show');
Route::get('editGenre/{genre}',[GenreController::class, 'edit'])->name('edit');
Route::put('editGenre/{genre}',[GenreController::class, 'update'])->name('update');
Route::delete('/{genre}',[GenreController::class, 'destroyGenre'])->name('destroyGenre');

resources/views/crudGenre/create.blade.php
@extends('crudGenre.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Genre</h2>
        </div>
    </div>
</div>
     
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
     
<form action="{{ route('genres.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center m-3">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-primary" href="{{ route('index') }}"> Back</a>
        </div>
    </div> 
</form>
@endsection 

resources/views/crudGenre/edit.blade.php
@extends('crudGenre.layout')
     
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Genre</h2>
            </div>
        </div>
    </div>
     
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    <form action="{{ route('update',$genre->id) }}" method="POST" enctype="multipart/form-data"> 
        @csrf
        @method('PUT')
     
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $genre->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12 text-center m-3">
              <button type="submit" class="btn btn-primary">Submit</button>
              <a class="btn btn-primary" href="{{ route('index') }}"> Back</a>
            </div>
        </div>
     
    </form>
@endsection

resources/views/crudGenre/index.blade.php
@extends('crudGenre.layout')
     
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Index</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('create') }}">Create New Genre</a>
            </div>
        </div>
    </div>
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
     
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($genres as $genre)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $genre->name }}</td>
            <td>
                <form action="{{ route('destroyGenre',$genre->id) }}" method="POST">
                    <a class="btn btn-info" href="{{ route('show',$genre->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('edit',$genre->id) }}">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    
    {!! $genres->links() !!}
        
@endsection

resources/views/crudGenre/layout.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap Link -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

  <title>Hanflix | Watch Movie for free | Livestream</title>
</head>
<body>
  <div class="container">
    @yield('content')
  </div>
</body>
</html>

resources/views/crudGenre/show.blade.php
@extends('crudGenre.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Genre</h2>
            </div>
        </div>
    </div>
     
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $genre->name }}
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('index') }}"> Back</a>
            </div>
        </div>
    </div>
@endsection